services:
  - type: web
    name: blood-bank-frontend
    env: static
    buildCommand: npm install && npm run build
    publishCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://blood-bank-management-system-backend-r7cp.onrender.com
